quay:
  namespace: quay-enterprise
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: false
    - name: postgres
      managed: true
    - name: redis
      managed: true
    - name: objectstorage
      managed: true
    - name: route
      managed: true
    - name: tls
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      # Generated password is saved to the 'quay-init-token' secret in the configured namespace
      name: quayadmin
      email: quayadmin@example.com
    user:
      # Generated password is saved to the 'quay-user' secret in the configured namespace
      # The API only allows the creation of superusers
      name: developer1
      email: developer1@myorg.com

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

global:
  hub:
    clustername: NAME
    domain: DOMAIN

  quay:
    org:
      name: devel
      email: devel@myorg.com
    repo: example

clusterGroup:
  name: AUTOMATIC

param:
  
  FEATURE_USER_INITIALIZE: true
  FEATURE_GENERAL_OCI_SUPPORT: true
  BROWSER_API_CALLS_XHR_ONLY: false
  SUPER_USERS:
  - quayadmin
  FEATURE_USER_CREATION: true
  ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
  AUTHENTICATION_TYPE: Database
  DEFAULT_TAG_EXPIRATION: 2w
  ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-
  FEATURE_BUILD_SUPPORT: false
  FEATURE_DIRECT_LOGIN: true
  FEATURE_MAILING: false
  REGISTRY_TITLE: Red Hat Quay
  REGISTRY_TITLE_SHORT: Quay
  TEAM_RESYNC_STALE_TIME: 60m
  TESTING: false
  CREATE_NAMESPACE_ON_PUSH: true  

  #  ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
  #  AUTHENTICATION_TYPE: Database
  #  DEFAULT_TAG_EXPIRATION: 2w
  #  ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
  #  # FEATURE_BUILD_SUPPORT: false
  #  FEATURE_DIRECT_LOGIN: true
  #  FEATURE_MAILING: false
  #  REGISTRY_TITLE: Red Hat Quay
  #  REGISTRY_TITLE_SHORT: Red Hat Quay
  #  TAG_EXPIRATION_OPTIONS: 2w
  #  TEAM_RESYNC_STALE_TIME: 60m
  #  TESTING: false
  #  #SERVER_HOSTNAME : quay-registry-quay-quay-enterprise.apps.npss-tnc-4.blueprints.rhecoeng.com 
  #  # enable 1st user creation with API 
  #  FEATURE_USER_INITIALIZE: true
  #  
  #  # enable API access
  #  BROWSER_API_CALLS_XHR_ONLY: false
  #  
  #  # Assign super user privilege to the the following user
  #  SUPER_USERS: quay
  #  
  #  # restrict user creation to super user group
  #  #FEATURE_USER_CREATION: false
  #  
  #  
  #  FEATURE_QUOTA_MANAGEMENT: true
  #  FEATURE_BUILD_SUPPORT: true
  #  FEATURE_PROXY_CACHE: true
  #  #FEATURE_STORAGE_REPLICATION: true
  #  DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
  #  
  #  
  #  FEATURE_REPO_MIRROR: true
  #  REPO_MIRROR_INTERVAL: 30
  #  REPO_MIRROR_SERVER_HOSTNAME: quay-registry-quay-quay-enterprise.apps.npss-tnc-4.blueprints.rhecoeng.com
  #  REPO_MIRROR_TLS_VERIFY: false
  #  REPO_MIRROR_ROLLBACK: true
  #  
  #  CREATE_NAMESPACE_ON_PUSH: true
  #  # auto create org if not exist when pushing
  #  FEATURE_GENERAL_OCI_SUPPORT: true
  #  #support hrlm artifact and other
  #  FEATURE_USER_CREATION: true
  #  #allow user creations by non super users



  
