apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: apps-nad
  namespace: mano-apps
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-apps
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "apps-nad",
    "type": "bridge",
    "bridge": "br-apps",
    "ipam": {
      "type": "static",
      "addresses": [ { "address": "10.60.3.0/24" } ]
      },
    "capabilities": { "ips": true }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: automation-nad
  namespace: mano-automation
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-automation
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "automation-nad",
    "type": "bridge",
    "bridge": "br-automation",
    "ipam": {
      "type": "static",
      "addresses": [ { "address": "10.60.4.0/24" } ]
      },
    "capabilities": { "ips": true }
    }'

